version: "3.8"

services:
  web:
    image: ${DOCKER_REGISTRY_SERVER}/sdg-innovation-commons:${IMAGE_TAG}
    ports:
      - "80:3000"
    restart: always

  worker:
    image: ${DOCKER_REGISTRY_SERVER}/sdg-innovation-commons-worker:${IMAGE_TAG}
    restart: always
    command: sh -c "node scripts/worker_http.js & node scripts/worker_heartbeat.js & node scripts/run_worker.js"
